name: Unit Test

on:
  push:
    branches:
    - master
    paths-ignore:
    - "docs/**"
    - "*.md"
  pull_request:
    branches:
    - master
    paths-ignore:
    - "docs/**"
    - "*.md"

jobs:
  unit-test:
    strategy:
      matrix:
        php_version:
          - 7.3
          - 7.4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: graycoreio/github-actions-magento2/unit-test@main
      with:
        php_version: ${{ matrix.php_version }}
        composer_auth: ${{ secrets.COMPOSER_AUTH }}
        test_command: ./vendor/bin/phpunit Test/Unit