name: Unit Tests
on: [pull_request,workflow_dispatch]
jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: https://repo.magento.com/
      MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
      MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
      MODULE_NAME: Pureclarity_Core
      COMPOSER_NAME: pureclarity/pureclarity-magento-2
      INPUT_MAGENTO_PRE_INSTALL_SCRIPT: .github/workflows/scripts/require.sh
      
    strategy:
      matrix:
        magento: ['2.2.11', '2.3.7-p1', '2.4.3']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Run PHP 7.2 Tests
        if: contains(matrix.magento, '2.2')
        uses: docker://ghcr.io/pureclarity/github-actions-magento-unit-tests:7.2
        env:
          MAGENTO_VERSION: ${{ matrix.magento }}
      - name: Run PHP 7.3 Tests
        if: contains(matrix.magento, '2.3')
        uses: docker://ghcr.io/pureclarity/github-actions-magento-unit-tests:7.3
        env:
          MAGENTO_VERSION: ${{ matrix.magento }}
      - name: Run PHP 7.4 Tests
        if: contains(matrix.magento, '2.4')
        uses: docker://ghcr.io/pureclarity/github-actions-magento-unit-tests:7.4
        env:
          MAGENTO_VERSION: ${{ matrix.magento }}
